services:

  server:
    container_name: django_server
    build: .
      #    command: bash -c "gunicorn -c gunicorn.conf.py enviroapp.wsgi"
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8088 --noreload"
    volumes:
      - /var/run/gunicorn:/var/run/gunicorn:rw
      - .:/code
    ports:
      - "8088:8088"
    #    depends_on:
    #      - db
    restart: always
    env_file:
      - .env
    networks:
      - hub-network
    depends_on:
      - mqtt-broker

  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - hub-network
    restart: always


  simulator:
    build: ./hub_image/
    container_name: hub_simulator
    volumes:
      - ./app:/src
    command: python /src/hub_simulator.py "test_hub" 10
    networks:
      - hub-network

networks:
  hub-network:
    driver: bridge